Adição do roteiro da entrevista sobre a Síndrome da Impostora
BOSS-BigOpenSourceSister/BigSister pull request #100
Opened 2020-10-12 13:08 UTC by mariav-flor

Adição do roteiro da entrevista do episódio da Talk Like a Boss sobre a Síndrome da Impostora, com a Juliana Aguiar.

2020-10-12 14:01 UTC, RafaellaJunqueira commented
Boa! Tem só uns conflitos, você pode resolver antes? 
É só clicar em "resolve conflicts" e ele vai te mostrar a diferença entre o que tem no seu doc e o que tem no doc que existe na main. Vai escolhendo as partes que quer manter e apagando as que não quiser. Não se esqueça de apagar os "===" e os "<<<". Qualquer dúvida, chama lá que a gente ajuda!

2020-10-14 22:48 UTC, Joranhezon requested changes
Faltou só adicionar o roteiro e o link dessa talk lá na tabelinha no readme da Talk Like a BOSS.

Fora isso, tá top. Muito obrigada por mandar! :smile_cat:

2020-10-14 22:48 UTC, Joranhezon commented on README.md
> +<img align = 'right' alt = "logo do programa de mentoria BOSS" src="https://pbs.twimg.com/profile_images/1293316517606633472/XaXs5OXJ_400x400.png" width = "180"/>
Pode trocar `programa` por `Iniciativa`, por favor? Fizemos essa troca em outros lugares pra ficar um artigo """feminino""" pra BOSS e acabamos esquecendo aqui.

2020-10-21 00:35 UTC, mariav-flor commented on README.md
> +<img align = 'right' alt = "logo do programa de mentoria BOSS" src="https://pbs.twimg.com/profile_images/1293316517606633472/XaXs5OXJ_400x400.png" width = "180"/>
boa! <3

2020-10-21 01:12 UTC, RafaellaJunqueira approved these changes
Maravilhosa!

2020-10-21 12:19 UTC, Joranhezon requested changes
Faltou apenas colocar os links na tabelinha no readme da [Talk Like a BOSS](https://github.com/BOSS-BigOpenSourceSister/BigSister/tree/main/talk_like_a_boss)

2020-10-24 20:31 UTC, RafaellaJunqueira approved these changes

2020-10-24 21:19 UTC, Joranhezon approved these changes
Boa, @mariav-flor ! Obrigada! 💖💖💖

2020-10-24 21:19 UTC, merged