Atualizando Readme do Big Sister
BOSS-BigOpenSourceSister/BigSister pull request #65
Opened 2020-09-15 22:20 UTC by mariav-flor

com @giovanadionisio 

Atualizamos o README do BigSister com informações mais completas e dados mais atuais.

**Issue relacionada**
https://github.com/BOSS-BigOpenSourceSister/BigSister/issues/62

2020-09-15 22:52 UTC, Joranhezon requested changes
Adorei a iniciativa em vir abrir um PR, mas não só isso, fazer um pareamento com a @giovanadionisio.

Sério, estou muito feliz. Vamos juntas! :smile:

2020-09-15 22:52 UTC, Joranhezon commented on README.md
> +O BOSS (Big Open Sister) é um programa de mentoria que visa engajar grupos sub representados na tecnologia para que comecem a contribuir para comunidades Open Source.
A Boss é uma mulher! hehe

2020-09-15 22:52 UTC, Joranhezon commented on README.md
> +Nessa mentoria, **muito mais do que desenvolver habilidades técnicas, é preciso ter outras competências com as quais as comunidades Open Source já estão acostumadas**, e outras estão tendo que se ade
Acho que podemos reestruturas essa frase `**muito mais do que desenvolver habilidades técnicas, é preciso ter outras competências com as quais as comunidades Open Source já estão acostumadas**, e outras estão tendo que se adequar agora.`. Ela deixa a entender que a mentorada já precisa saber isso previamente, enquanto na verdade, é nossa responsabilidade como mentoras ajudar vocês a conseguirem essas habilidades. Colocar algo como `muito mais do que desenvolver habilidades técnicas, as participantes vão aprender habilidades como....`

Também podemos explicitar essas outras habilidades, algo como: se comunicar, trabalhar de maneira assincrona, trabalho remoto, etc.

2020-09-15 22:52 UTC, Joranhezon commented on README.md
> +**As inscrições para esta edição do programa estão encerradas**. Quando uma nova seleção for aberta, disponibilizaremos o link  para inscrição em nossos canais de comunicação.
Nice! :rainbow: :heart_eyes:

2020-09-15 22:52 UTC, Joranhezon commented on README.md
> +O programa é focado em minorias: **mulheres, negros, comunidade LGBTQA+**.
Vamos elaborar um pouquinho mais essa aqui? Acho que poderia ser um textinho mesmo, falarmos que o programa é focado em trazer pra tecnologia todos os grupos que sofrem discriminação sistemica. Ai podemos também falar que **convidamos** mulheres cis e trans, negros, imigrantes, homens trans, gays, lésbicas e comunidade LGBTQA+ em geral.

Acho que assim fica mais convidativo, e passa uma idéia de comunidade que está tentando acolher essas pessoas. Do jeito que está parece meio...frio. Fez sentido?

2020-09-16 14:33 UTC, mariav-flor commented on README.md
> +O BOSS (Big Open Sister) é um programa de mentoria que visa engajar grupos sub representados na tecnologia para que comecem a contribuir para comunidades Open Source.
uhu!!! ok!

2020-09-16 14:34 UTC, mariav-flor commented on README.md
> +Nessa mentoria, **muito mais do que desenvolver habilidades técnicas, é preciso ter outras competências com as quais as comunidades Open Source já estão acostumadas**, e outras estão tendo que se ade
Boa ideia, anotando...

2020-09-16 14:35 UTC, mariav-flor commented on README.md
> +O programa é focado em minorias: **mulheres, negros, comunidade LGBTQA+**.
Perfeito, super topo de fazermos essas mudanças na mesma branch contigo, Ma!

2020-09-17 10:53 UTC, Joranhezon approved these changes
Muito bom, @mariav-flor @giovanadionisio! Muito obrigada por terem contribuido. :heart: :rainbow:

2020-09-17 10:53 UTC, merged